services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=has123321
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hashemnasrallah2005
      - MONGO_INITDB_ROOT_PASSWORD=H@$hemHx8i
    ports:
      - "27017:27017"
    volumes:
      - /data/db