services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=has123321
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"